---
name: Luarocks Check Versions

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

defaults:
  run:
    working-directory: openid-connect-provider-debugger

jobs:
  luarocks-check-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Check the versions
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
	  rc=0
          \sudo apt install -y luarocks
          \lua -e 'dofile("/tmp/openid-connect-provider-debugger-0.0.0.rockspec"); for _, dep in ipairs(dependencies) do local package, version = dep:match("^(.+)%s*==%s*(.+)$"); if package and version then print(package .. " " .. version) end end' | while read package current_version ; do
            latest_version="$(\luarocks search "${package}" --porcelain | \head -n 1 | \cut -f 2)"
            if [ "${current_version}" != "${latest_version}" ]; then
              echo "${package} ${current_version} -> ${latest_version}"
              rc=$((rc+1))
            fi
          done
          exit ${rc}
